### ISSUE TITLE
您好，pdf好像都已经失效了

### ISSUE THREAD

**Issue by ghost** [dick20/MCM-ICM#2]
如题。能烦请重新上传或其他解决办法吗？谢谢您。

**Comment by HoniiTro19** [comment]
你好，我这维护了2004-2020美赛O奖论文，可到我主页查看。

**Comment by Luokang173** [comment]
怎么了没看邮箱




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Murphy-OrangeMud"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 上午10:15
收件人:&nbsp;"dick20/MCM-ICM"<MCM-ICM@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[dick20/MCM-ICM] 您好，pdf好像都已经失效了 (#2)





 
如题。能烦请重新上传或其他解决办法吗？谢谢您。

**Comment by dick20** [comment]
已更新
